name: Active releases

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Setup node 10.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - name: Build docker image
        run: docker build --tag weisong0908/common-shop-web-client .
      - name: Login to Docker Hub with access token
        run: docker login -u weisong0908 -p ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - name: Push docker image to Docker Hub
        run: docker push weisong0908/common-shop-web-client
  deploy:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Executes remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_SERVERADDRESS }}
          username: weisong0908
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          port: 22
          script: |
            docker stop common-shop-web-client
            docker rm common-shop-web-client
            docker pull weisong0908/common-shop-web-client
            docker run -d -p 8080:80 --name common-shop-web-client weisong0908/common-shop-web-client
